SECRET_KEY = "you-will-never-guess"
JSON_AS_ASCII = False

ITEMS_PER_PAGE = 12

TOKEN_EXPIRE_MINUTES = 15
TOKEN_EXPIRE_DAYS = 130

PWD_HASH_SALT = b'secret here'
PWD_HASH_ITERATIONS = 100_000
PWD_HASH_NAME = 'sha256'
AlGORITM = 'HS256'