version: '3.9'
services:
  web:
    image: tsorokoletova/lesson26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - '8080:80'
    restart: always
    depends_on:
      - pg
  pg:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
